### ISSUE TITLE
Initial todo list

### ISSUE THREAD

**Issue by donquixote** [donquixote/drupal-renderkit#1]
Library:
- [x] ListFormat interface
  - [x] ItemList / ul / ol
  - [x] ContainerList
  - [x] SeparatorList
- [x] EntityDisplay contextual links
- [x] EntityToEntity relationship

Drupal integration:
- [x] EntityDisplay Views row plugin
- [x] EntityDisplay Views field plugin
- [x] EntityDisplay Entityreference formatter
- [ ] EntityDisplay field type
- [ ] Listformat plugin type
- [ ] Listformat views style plugin
- [ ] Listformat field theme function (ds)
- [ ] Listformat field type

Bikeshed / future:
- Object instead of render array?
- EntityWrapper object, instead of specifying type name + entity?
- RenderElement, PreRenderInterface, ThemePreprocessInterface, ThemeProcessInterface?
